num_humans: 1 #number of human controlled robots
num_ais: 1 #number of ai controlled robots
width: 800 #width of camera view
height: 600 #height of camera view
timer: 10000 #play time in seconds
cell_size: 0.5 #Cell size for occupancy map
sensor_waiting_time: 0 #How much time to wait until sensor becomes available again after usage
